# Tensorflow like Numpy

In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [2]:
!pip list | grep tensor

tensorboard                                2.4.0
tensorboard-plugin-wit                     1.7.0
tensorflow                                 2.4.0
tensorflow-estimator                       2.4.0


In [3]:
import tensorflow as tf

In [5]:
tf.config.get_visible_devices("CPU"), tf.config.get_visible_devices("GPU")

([PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')],
 [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')])

In [6]:
# This would make the computations run on CPU
tf.config.set_visible_devices([], "GPU")

In [7]:
tf.config.get_visible_devices("CPU"), tf.config.get_visible_devices("GPU")

([PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')], [])

## Immutable tensors

In [8]:
arr = tf.constant(range(1, 11), dtype=tf.float64)
arr.shape

TensorShape([10])

In [10]:
arr.dtype

tf.float64

In [9]:
arr = tf.reshape(arr, (2, 5))
arr

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])>

In [14]:
# indexing works similar to numpy array
arr[1, 1]
arr[:, 2:4]
arr[..., 1]

<tf.Tensor: shape=(), dtype=float64, numpy=7.0>

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3., 4.],
       [8., 9.]])>

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([2., 7.])>

In [15]:
# adding new axis
t = arr[..., 1, tf.newaxis]
t.shape
t

TensorShape([2, 1])

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[2.],
       [7.]])>

In [17]:
tf.transpose(arr)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]])>

In [18]:
tf.matmul(arr, tf.transpose(arr))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 55., 130.],
       [130., 330.]])>

In [19]:
arr ** 2

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[  1.,   4.,   9.,  16.,  25.],
       [ 36.,  49.,  64.,  81., 100.]])>

In [21]:
# Calculating max, mean, sum
# Perform max, sum and mean along the first axis(dimension)
# which is along the rows for a matrix
tf.reduce_max(arr, axis=0)
tf.reduce_sum(arr, axis=0)
tf.reduce_mean(arr, axis=0)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 6.,  7.,  8.,  9., 10.])>

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 7.,  9., 11., 13., 15.])>

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([3.5, 4.5, 5.5, 6.5, 7.5])>

In [22]:
# mathematical operations
tf.math.log(arr)

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])>

## Keras low level APIs

In [23]:
# For the code to work in other keras implementations
# we need to use low level operations defined in keras package
from tensorflow.keras import backend as K

# all low level apis are available in keras.backend
K.square(arr)
K.transpose(arr)

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[  1.,   4.,   9.,  16.,  25.],
       [ 36.,  49.,  64.,  81., 100.]])>

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]])>

## Tensors and Numpy

It is possible to create tensors from numpy array and vice versa.

In [24]:
import numpy as np

In [28]:
# convert numpy array to tensor
np_arr = np.arange(1, 11, dtype=np.int64)
tf_arr = tf.constant(np_arr)
tf_arr.dtype  # numpy array type is preserved
tf_arr.shape

tf.int64

TensorShape([10])

In [29]:
# applying tensorflow operations on numpy arrays
tf.square(np_arr)
# applying numpy operations on tensors
np.square(tf_arr)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])>

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Tensor operations work on tensors of exactly same datatype. Even adding a float32 and float64 tensors would raise error.

In [31]:
# to add tensors of different types we need to use tf.cast
tf_float_arr = tf.cast(tf_arr, dtype=tf.float32)
tf_arr.dtype, tf_float_arr.dtype

(tf.int64, tf.float32)

## Variables in tensorflow

In [35]:
# initial_value, dtype, shape, trainable are some of the
# important parameters
# shape should match the initial_value shape
tf_var = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float64, shape=(2, 3))

In [36]:
tf_var.shape

TensorShape([2, 3])

In [41]:
# we cannot assign like this to a tensor
# we have to use the assign method
tf_var[1, 2] = 10

TypeError: 'ResourceVariable' object does not support item assignment

In [37]:
# variables are mutable
# inplace modification using assign method
tf_var.assign(2 * tf_var)
tf_var

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float64, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])>

In [40]:
# modify a subset
# replace a particular element
tf_var[1, 2].assign(100)
# replace second column with
tf_var[:, 1].assign([1, 1])
tf_var

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float64, numpy=
array([[  2.,   4.,   6.],
       [  8.,  10., 100.]])>

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float64, numpy=
array([[  2.,   1.,   6.],
       [  8.,   1., 100.]])>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[  2.,   1.,   6.],
       [  8.,   1., 100.]])>

In [42]:
tf_var.scatter_nd_update(indices=[[0, 0], [0, 2]], updates=[300, 400])
tf_var

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float64, numpy=
array([[300.,   1., 400.],
       [  8.,   1., 100.]])>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[300.,   1., 400.],
       [  8.,   1., 100.]])>

## Other data structures

* `tf.SparseTensor`, operations available at `tf.sparse`
* `tf.TensorArray`
* `tf.RaggedTensor` - operations on these tensors are available at `tf.ragged`
* String tensors under `tf.string` package
* Sets - operations under `tf.sets` package
* Queues - operations are available under `tf.queues` package
