# Pandas Tutorial

Pandas has built-in two dimensional data structure called a Dataframe.

## Pandas Series

Series is similar to numpy arrays, except we can give named or datetime as index instead of just a numerical index.

* Numpy arrays should contain only values of the same data type.
* Pandas series are highly flexible

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ["a", "b", "c"]
values = [10, 20, 30]

# pandas series are very similar to numpy arrays
pandas_series = pd.Series(values, index=labels)
pandas_series

a    10
b    20
c    30
dtype: int64

In [3]:
# we can use labels as index to refer to the value
pandas_series["a"]

10

In [4]:
# we can also use the numerical index
pandas_series[0]

10

In [5]:
# we can also create a pandas series from python dictionary
series_from_dict = pd.Series({"a": 10, "b": 20, "c": 30})
series_from_dict

a    10
b    20
c    30
dtype: int64

## Pandas dataframe

* Pandas dataframes are similar to numpy 2dimensional arrays but with much more functionality.
* Pandas dataframe is a two-dimensional data structure that has labels for both its rows and columns.
* Pandas dataframe can be thought of as collection of pandas series

In [6]:
rows = ["X", "Y", "Z"]
columns = ["A", "B", "C", "D", "E"]

values = np.random.default_rng().integers(1, 100, (3, 5))
print(values)

df = pd.DataFrame(values, rows, columns)
df.head()

[[16  2  7 69 61]
 [90 20 52 55 41]
 [84 52  3 80 51]]


,A,B,C,D,E
X,16,2,7,69,61
Y,90,20,52,55,41
Z,84,52,3,80,51


## Indexing and assignment in Pandas dataframes

In [7]:
# we can refer to any column using the column labels inside []
df["A"]

X    16
Y    90
Z    84
Name: A, dtype: int64

In [8]:
# we can also select a list of columns
df[["A", "B"]]

,A,B
X,16,2
Y,90,20
Z,84,52


In [9]:
# You can also select a specific element of a specific row
# using chained square brackets.
df["A"]["X"]

16

## Create and remove columns in a dataframe

In [10]:
# adding a column with label "A+B" from existing columns A and B
df["A+B"] = df["A"] + df["B"]
df["A+B"]

X     18
Y    110
Z    136
Name: A+B, dtype: int64

In [11]:
# by default drop will drop rows
# drop does not modify the original dataframe
# it returns a dataframe with the specific column removed
df.drop("X")
# deletes row with index X
df.drop(index=["X"])

,A,B,C,D,E,A+B
Y,90,20,52,55,41,110
Z,84,52,3,80,51,136


In [12]:
# To remove a column we should set the axis to 1
df.drop("A+B", axis=1)

# This is easier and more readable. No need to remember the axis
df.drop(columns=["A+B"])

,A,B,C,D,E
X,16,2,7,69,61
Y,90,20,52,55,41
Z,84,52,3,80,51


In [13]:
# below code deletes the column from the dataframe inplace
# df.drop("A+B", axis=1, inplace=True)
# or we can overwrite the variable reference to modified dataframe
df = df.drop("A+B", axis=1)
df

,A,B,C,D,E
X,16,2,7,69,61
Y,90,20,52,55,41
Z,84,52,3,80,51


## Select a row from a pandas dataframe

In [14]:
# dataframe rows accessed usig the loc attribute
df.loc["X"]

A    16
B     2
C     7
D    69
E    61
Name: X, dtype: int64

In [15]:
# if we want to access the dataframe row using index
df.iloc[0]

A    16
B     2
C     7
D    69
E    61
Name: X, dtype: int64

## Number of rows and columns in the dataframe

In [16]:
df.shape

(3, 5)

## Slicing pandas dataframe

In [17]:
# we can use the numpy indexing
# select all the rows but only first two columns
df.iloc[:, :2]

,A,B
X,16,2
Y,90,20
Z,84,52


In [18]:
# this will return a copy because we are using list inside the index
df.loc[["X", "Y"], ["A", "B", "C"]]

,A,B,C
X,16,2,7
Y,90,20,52


## Conditional selection using pandas dataframe

In [19]:
# returns a boolean dataframe where each entry is either True or False
# very similar to numpy arrays and conditions
df > 50

,A,B,C,D,E
X,False,False,False,True,True
Y,True,False,True,True,False
Z,True,True,False,True,True


In [20]:
# we can also use the condition inside []
# when the condition is not satisfied by the entry
# the entry is replaced with NaN
df[(df > 50) & (df < 75)]

,A,B,C,D,E
X,NaN,NaN,NaN,69.0,61.0
Y,NaN,NaN,52.0,55.0,NaN
Z,NaN,52.0,NaN,NaN,51.0


In [21]:
# select specific column and apply condition
print(df["C"] < 75)

# we can apply condition to any subset of dataframe
df.iloc[:, 1:4] < 75

X    True
Y    True
Z    True
Name: C, dtype: bool


,B,C,D
X,True,True,True
Y,True,True,True
Z,True,True,False


In [22]:
# This will select enties as per the boolean matrix returned by the condition
print(df[df.iloc[:, 1:4] < 75])

# condition applied to subset of dataframe
df.iloc[:, 1:4][df.iloc[:, 1:4] < 75]

    A   B   C     D   E
X NaN   2   7  69.0 NaN
Y NaN  20  52  55.0 NaN
Z NaN  52   3   NaN NaN


,B,C,D
X,2,7,69.0
Y,20,52,55.0
Z,52,3,NaN


In [23]:
# rows corresponding to the output of the condition is returned
df[(df["C"] > 50) & (df["A"] < 75)]

,A,B,C,D,E


## Modify the index(row labels) of the pandas dataframe

In [24]:
# prints the row labels or named indices
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [25]:
# remove labels using reset_index() method
# does not modify the dataframe inplace unless explicitly specified
# adds an index column to hold the old indices
tempdf = df.reset_index()
print(df)

print("========================")
print(tempdf)

    A   B   C   D   E
X  16   2   7  69  61
Y  90  20  52  55  41
Z  84  52   3  80  51
  index   A   B   C   D   E
0     X  16   2   7  69  61
1     Y  90  20  52  55  41
2     Z  84  52   3  80  51


In [26]:
# we can also use an existing column values to act as index
# whatever the values of column A becomes the label for rows
tempdf = df.set_index("A")
print(tempdf.index)
# selects first row based on new label
tempdf.loc[tempdf.index[0], :]
# tempdf.loc[]

Int64Index([16, 90, 84], dtype='int64', name='A')


B     2
C     7
D    69
E    61
Name: 16, dtype: int64

## Rename columns in pandas dataframe

In [27]:
# gets all the column labels
df.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [28]:
# rename by assigning new column labels list to the columns attribute
df.columns = ["H", "I", "J", "K", "L"]
df

,H,I,J,K,L
X,16,2,7,69,61
Y,90,20,52,55,41
Z,84,52,3,80,51


## Deal with missing data in the pandas dataframes

In [29]:
data = np.array([[1, 5, 1], [2, np.nan, 2], [np.nan, np.nan, 3]])

df = pd.DataFrame(data)
df.columns = ["A", "B", "C"]

df

,A,B,C
0,1.0,5.0,1.0
1,2.0,NaN,2.0
2,NaN,NaN,3.0


In [30]:
# dropna method removes any rows that contain NaN value
# Note that like the other DataFrame operations that we have explored,
# dropna does not modify the original DataFrame unless you either
# (1) force it to using the = assignment operator or
# (2) specify inplace=True.

df.dropna()

,A,B,C
0,1.0,5.0,1.0


In [31]:
# drop only the columns with missing values by setting the axis = 1
df.dropna(axis=1)

,C
0,1.0
1,2.0
2,3.0


In [32]:
# In many cases, you will want to replace missing values
# in a pandas DataFrame instead of dropping it completely.
# The fillna method is designed for this.
df.fillna(0)  # fills NaN with 0

,A,B,C
0,1.0,5.0,1.0
1,2.0,0.0,2.0
2,0.0,0.0,3.0


In [33]:
# More often we will replace a missing value with either:
# The average value of the entire DataFrame
# The average value of that row of the DataFrame

df.fillna(df.mean())

,A,B,C
0,1.0,5.0,1.0
1,2.0,5.0,2.0
2,1.5,5.0,3.0


In [34]:
col_a_mean = df["A"].mean()
print(col_a_mean)
# compute the mean, fill and replace the column
df["A"] = df["A"].fillna(col_a_mean)
df

1.5


,A,B,C
0,1.0,5.0,1.0
1,2.0,NaN,2.0
2,1.5,NaN,3.0


##  `groupby` feature

In [35]:
df = pd.DataFrame(
    [
        ["Google", "Sam", 200],
        ["Google", "Charlie", 120],
        ["Salesforce", "Ralph", 125],
        ["Salesforce", "Emily", 250],
        ["Adobe", "Rosalynn", 150],
        ["Adobe", "Chelsea", 500],
    ]
)

df.columns = ["Organization", "Salesperson Name", "Sales"]

df

,Organization,Salesperson Name,Sales
0,Google,Sam,200
1,Google,Charlie,120
2,Salesforce,Ralph,125
3,Salesforce,Emily,250
4,Adobe,Rosalynn,150
5,Adobe,Chelsea,500


In [36]:
df.groupby("Organization").mean("Sales")

,Sales
Organization,
Adobe,325.0
Google,160.0
Salesforce,187.5


In [37]:
df.groupby("Organization").sum("Sales")

# we also have count, min, max, std(standard deviation) methods
# documentation on methods available on the groupby object can be
# found at
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.apply.html

,Sales
Organization,
Adobe,650
Google,320
Salesforce,375


In [38]:
# the describe method, which returns useful information
# for every category that the
# groupby function is working with.
df.groupby("Organization").describe()

Sales                                                        
             count   mean         std    min     25%    50%     75%    max
Organization                                                              
Adobe          2.0  325.0  247.487373  150.0  237.50  325.0  412.50  500.0
Google         2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
Salesforce     2.0  187.5   88.388348  125.0  156.25  187.5  218.75  250.0

## `concat` method

In [39]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

In [40]:
# takes axis = 0  by default
# This is similar to union of multiple tables with same schema
pd.concat([df1, df2, df3])

,A,B,C,D
0,A0,B0,C0,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3
4,A4,B4,C4,D4
5,A5,B5,C5,D5
6,A6,B6,C6,D6
7,A7,B7,C7,D7
8,A8,B8,C8,D8
9,A9,B9,C9,D9


In [41]:
# along axis = 1
pd.concat([df1, df2, df3], axis=1)

,A,B,C,D,A,B,C,D,A,B,C,D
0,A0,B0,C0,D0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A1,B1,C1,D1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A2,B2,C2,D2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A3,B3,C3,D3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,A4,B4,C4,D4,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,A5,B5,C5,D5,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,A6,B6,C6,D6,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,A7,B7,C7,D7,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A8,B8,C8,D8
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A9,B9,C9,D9


## Merging dataframes(sql inner join)

You can merge two pandas DataFrames along a common column using the merge columns. For anyone that is familiar with the SQL programming language, this is very similar to performing an join in SQL.

In [42]:
leftdf = pd.DataFrame(
    {"key": ["K0", "K1", "K2", "K4"], "A": ["A0", "A1", "A2", "A3"], "B": ["B0", "B1", "B2", "B3"]}
)
leftdf

,key,A,B
0,K0,A0,B0
1,K1,A1,B1
2,K2,A2,B2
3,K4,A3,B3


In [43]:
rightdf = pd.DataFrame(
    {"key": ["K0", "K1", "K2", "K3"], "C": ["C0", "C1", "C2", "C3"], "D": ["D0", "D1", "D2", "D3"]}
)
rightdf

,key,C,D
0,K0,C0,D0
1,K1,C1,D1
2,K2,C2,D2
3,K3,C3,D3


In [44]:
pd.merge(leftdf, rightdf, how="inner", on="key")

,key,A,B,C,D
0,K0,A0,B0,C0,D0
1,K1,A1,B1,C1,D1
2,K2,A2,B2,C2,D2


## Pandas `join` method

Commonly used to join dataframes based on index column(column containing row labels). But we can also specify a key column for join.

In [45]:
leftdf = pd.DataFrame(
    {"A": ["A0", "A1", "A2", "A3"], "B": ["B0", "B1", "B2", "B3"]}, index=["K1", "K2", "K0", "K4"]
)
leftdf

,A,B
K1,A0,B0
K2,A1,B1
K0,A2,B2
K4,A3,B3


In [46]:
rightdf = pd.DataFrame(
    {"C": ["C0", "C1", "C2", "C3"], "D": ["D0", "D1", "D2", "D3"]}, index=["K1", "K2", "K0", "K3"]
)
rightdf

,C,D
K1,C0,D0
K2,C1,D1
K0,C2,D2
K3,C3,D3


In [47]:
# join works on index column
# by default on = index column
# Performs left join by default
leftdf.join(rightdf, how="inner")

,A,B,C,D
K1,A0,B0,C0,D0
K2,A1,B1,C1,D1
K0,A2,B2,C2,D2


In [48]:
# sort by the join on column
leftdf.join(rightdf, how="inner", sort=True)

,A,B,C,D
K0,A2,B2,C2,D2
K1,A0,B0,C0,D0
K2,A1,B1,C1,D1


## Other commons operations in dataframe

In [49]:
df = pd.DataFrame(
    {"col1": ["A", "B", "C", "D"], "col2": [2, 7, 3, 7], "col3": ["fgh", "rty", "asd", "qwe"]}
)
df

,col1,col2,col3
0,A,2,fgh
1,B,7,rty
2,C,3,asd
3,D,7,qwe


In [50]:
# unique values in a pandas series
# unique method works only on series and not on dataframe
df["col2"].unique()

array([2, 7, 3])

In [51]:
# count of unique items
df["col2"].nunique()

3

In [52]:
# count of occurence of each value
df["col2"].value_counts()

7    2
2    1
3    1
Name: col2, dtype: int64

In [53]:
# apply method can be used to apply a builtin or a custom function
# on a pandas series
from typing import Union


def square(x: Union[np.int64, pd.Series]) -> Union[np.int64, pd.Series]:
    print(type(x), x)
    return x**2


# If we invoke, Series.apply, for every element in the series
# the function is called
df["col2"].apply(square)

# When we invoke DataFrame.apply, by default axis=0
# Every column gets passes to the function
# If we mention axis=1, then every row gets passed to the function
df[["col2"]].apply(square)

<class 'int'> 2
<class 'int'> 7
<class 'int'> 3
<class 'int'> 7
<class 'pandas.core.series.Series'> 0    2
1    7
2    3
3    7
Name: col2, dtype: int64


,col2
0,4
1,49
2,9
3,49


In [54]:
df["col3"].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [55]:
# sort dataframe based on column values using sort_values function
# to modify the dataframe inplace using option inplace = True
df.sort_values("col2")

,col1,col2,col3
0,A,2,fgh
2,C,3,asd
1,B,7,rty
3,D,7,qwe


## Local data IO in pandas

In [56]:
# read_csv, read_json, read_html, read_excel methods available
stock_prices = pd.read_csv("stock_prices.csv")
stock_prices.head()

# export using stock_prices.to_csv(output_filename)

,Period,Alphabet Inc Price,Amazon.com Inc Price,Facebook Inc Price,Microsoft Corp Price
0,2020-04-06 00:00:00,1167.15,1970.70,163.00,161.59
1,2020-04-03 00:00:00,1097.88,1906.59,154.18,153.83
2,2020-04-02 00:00:00,1120.84,1918.83,158.19,155.26
3,2020-04-01 00:00:00,1105.62,1907.70,159.60,152.11
4,2020-03-31 00:00:00,1162.81,1949.72,166.80,157.71


In [57]:
stock_prices_json = pd.read_json("stock_prices.json")
stock_prices_json.head()

# export using stock_prices.to_json(output_filename)

,Period,Alphabet Inc Price,Amazon.com Inc Price,Facebook Inc Price,Microsoft Corp Price
0,2020-04-06 00:00:00,1167.15,1970.70,163.00,161.59
1,2020-04-03 00:00:00,1097.88,1906.59,154.18,153.83
2,2020-04-02 00:00:00,1120.84,1918.83,158.19,155.26
3,2020-04-01 00:00:00,1105.62,1907.70,159.60,152.11
4,2020-03-31 00:00:00,1162.81,1949.72,166.80,157.71


In [58]:
# While importing Excel documents, it is very important to note
# that pandas only imports data. It cannot import other Excel
# capabilities like formatting, formulas, or macros.
# Trying to import data from an Excel document that has
# these features may cause pandas to crash.
stock_prices_excel = pd.read_excel("stock_prices.xlsx")
stock_prices_excel.head()

# export using stock_prices.to_excel(output_filename, sheet_name = "excel_sheet")

,Unnamed: 0,Period,Alphabet Inc Price,Amazon.com Inc Price,Facebook Inc Price,Microsoft Corp Price
0,0,2020-04-06 00:00:00,1167.15,1970.70,163.00,161.59
1,1,2020-04-03 00:00:00,1097.88,1906.59,154.18,153.83
2,2,2020-04-02 00:00:00,1120.84,1918.83,158.19,155.26
3,3,2020-04-01 00:00:00,1105.62,1907.70,159.60,152.11
4,4,2020-03-31 00:00:00,1162.81,1949.72,166.80,157.71


## Remote data files

`read_csv`, `read_json`, `read_html`, `read_excel` methods support reading data from a URL and loading that data in to a dataframe.