# Numpy Tutorial

## 1-D array

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# contents of b and a are the same
b = np.array(range(0, 10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# An array can be indexed by a tuple of nonnegative integers,
# by booleans, by another array, or by integers
a[0]

0

In [4]:
# we can also use slice or list as index
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# gets the elements at index 1, 5 and 9
a[[1, 5, 9]]

array([1, 5, 9])

## Array dimensions

In [6]:
a.ndim

1

In [7]:
a.shape

(10,)

## 2-D array

In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
# Gives the array dimension
# Number of indices needed to get to the element
b.ndim

2

In [10]:
# Get the array shape in terms of rows and columns
b.shape

(2, 3)

In [11]:
# convert 2d to 1d array
b.ravel()

array([1, 2, 3, 4, 5, 6])

## 3-D array

In [12]:
# interpret arr as a collection of 2 (3,4) matrices
arr = np.arange(24).reshape(2, 3, 4)

# first matrix
print(arr[0])

# second matrix
print(arr[1])

# axis 0 will run downwards through each matrix
# axis 1 matrix row
# axis 2 matrix column
arr[0] + arr[1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [13]:
# same as arr[0] + arr[1]
arr.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
# first matrix first row
print(arr[0][0])

# This will collapse all rows in each matrix
# hence we get two lists in the summed output
# one for each matrix after collapsing rows
print(arr.sum(axis=1))

# first matrix axis 0 sum
print(arr[0].sum(axis=0))
print(arr[0][0] + arr[0][1] + arr[0][2])

# second matrix axis 0 sum
print(arr[1].sum(axis=0))
print(arr[1][0] + arr[1][1] + arr[1][2])

[0 1 2 3]
[[12 15 18 21]
 [48 51 54 57]]
[12 15 18 21]
[12 15 18 21]
[48 51 54 57]
[48 51 54 57]


## Array datatype, size and bytes

In [15]:
# dtype stands for datatype
a = np.array([1, 2, 3], dtype="int16")

In [16]:
# number of elements in the array
a.size

3

In [17]:
# datatype of the array
a.dtype

dtype('int16')

In [18]:
# item size in bytes
a.itemsize

2

In [19]:
# size of the array in bytes
a.nbytes

6

## Convert 1D array into 2D array

In [20]:
# np.newaxis and np.expand_dims are used to
# increase dimensions of existing array

# everytime np.newaxis is used on the array, the array dimension is
# increased by 1
vector = np.array([1, 2, 3, 4, 5, 6])
print(vector.shape)

# this is useful to convert a vector to
# either a row matrix or column matrix
# vector shape becomes (1, 6) from (6,)
row_matrix = vector[np.newaxis, :]
print(row_matrix.shape)

# vector shape becomes (6, 1) from (6, )
# column matrix/vector
column_matrix = vector[:, np.newaxis]
print(column_matrix.shape)

(6,)
(1, 6)
(6, 1)


In [21]:
# Imagine the shape of an ndarray to be a tuple
# and calling np.newaxis with a specific
# axis will introduce 1 at that index of the tuple(shape)
twod = np.array([[1, 2, 3], [4, 5, 6]])
# its a (2,3) matrix
print(twod.shape)

# (1, 2, 3) will be the shape
# notice np.newaxis is at index 0
print(twod[np.newaxis, :, :].shape)

# (2, 1, 3) will be the shape
# notice np.newaxis is at index 1
print(twod[:, np.newaxis, :].shape)

# (2, 3, 1) will be the shape
# notice np.newaxis is at index 2
print(twod[:, :, np.newaxis].shape)

(2, 3)
(1, 2, 3)
(2, 1, 3)
(2, 3, 1)


## Axes in numpy
Note axis refers to the index position of the dimension tuple. Suppose we have a three dimensional array `arr`. `axis=0` refers to `arr.shape[0]`, `axis=1` refers to `arr.shape[1]` and so on.

![row_and_column_axis](numpy_axes.jpg)

* Single point is always represented as an array
* List of points is represented using a 2d array

* Axis 0 is the first axis and its direction runs downwards along with rows. In a 2d-array, by changing the first index(first axis), we reach different rows

* Axis 1 is the second axis, and runs along the column sidewards. In a 2d-array, by changing the second index, we can numbers at reach different columns.

* Numpy array axes are numbered starting from 0.

**NOTE:** 1-DIMENSIONAL NUMPY ARRAYS ONLY HAVE ONE AXIS.
![1d Array](1d_array_axis.png)

---

### References
* [Numpy axes](https://www.sharpsightlabs.com/blog/numpy-axes-explained/) 

In [22]:
# expand an array by inserting new axis at a specified position using
# np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])

# a.shape is (6,)
# On expand_dims at axis=0, a.shape becomes(1,6)
# Notice 1 getting added to 0th dimension
r = np.expand_dims(a, axis=0)
print(r.shape)

# a.shape is (6,)
# On expand_dims at axis=1, a.shape becomes(6, 1)
# Notice 1 getting added to 1th dimension
c = np.expand_dims(a, axis=1)
print(c.shape)

(1, 6)
(6, 1)


In [23]:
# Imagine the shape of an ndarray to be a tuple
# and calling expand_dims with a specific
# axis will introduce 1 at that index of the tuple(shape)
# while shifting other elements after the axis index to their right
a = np.array([[1, 2], [3, 4]])
# a.shape is currently (2,2)
print(a.shape)

# a will now become (1, 2, 2). Notice 1 added to 0th index
print(np.expand_dims(a, axis=0).shape)

# a will now become (2, 1, 2). Notice 1 added to 1st index
print(np.expand_dims(a, axis=1).shape)

# a will now become (2, 2, 1). Notice 1 added to 2nd index
print(np.expand_dims(a, axis=2).shape)

(2, 2)
(1, 2, 2)
(2, 1, 2)
(2, 2, 1)


## Accessing array elements, rows and columns

In [24]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [25]:
# access an element using array[r, c]
arr[0, 2]  # first row and 3rd column value

3

In [26]:
# row and column indexes work with negative values as well
# negative values start from the end of the array
arr[-1, -1]

14

In [27]:
# we can also specify slice objects as part of the
# index to select set of rows and columns

# all the rows and first column only
arr[:, 0]

array([1, 8])

In [28]:
# all columns of the first row
arr[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# all columns of all rows except the last column
arr[:, :-1]

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13]])

In [30]:
# update a section of the array
# update the last column
arr[:, -1] = [20, 21]
arr

array([[ 1,  2,  3,  4,  5,  6, 20],
       [ 8,  9, 10, 11, 12, 13, 21]])

In [31]:
# understand it as list of matrices
ndim_arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype="int32")

In [32]:
# row, column, element list is the index order
# first row, first column, first element
ndim_arr[0, 0, 0]

1

In [33]:
# all rows second column all the elements
ndim_arr[:, 1, :]

array([[3, 4],
       [7, 8]], dtype=int32)

In [34]:
# update last rows of both matrices
ndim_arr[:, -1, :] = [[10, 10], [20, 20]]
ndim_arr

array([[[ 1,  2],
        [10, 10]],

       [[ 5,  6],
        [20, 20]]], dtype=int32)

In [35]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [36]:
# condition like this to filter the values
a[a < 5]

array([1, 2, 3, 4])

In [37]:
cond = a % 2 == 0
a[cond]

array([ 2,  4,  6,  8, 10, 12])

## Initializing different types of arrays

In [38]:
# fill a matrix with zeros
# create a 1d matrix of zeros
zero_arr = np.zeros(2, dtype="int16")
zero_arr

array([0, 0], dtype=int16)

In [39]:
# create a 2d matrix filled with zeros
zero_matrix = np.zeros((3, 3), dtype="int64")
zero_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
# fill all the elements with one
# here we create a 3 dimensional array
ones_matrix = np.ones((3, 3, 2))
print(ones_matrix.ndim)
ones_matrix

3


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [41]:
# uninitialized empty array. values are unpredictable.
np.empty((2, 3))

array([[4.65007399e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [42]:
# fill an ndimensional array with desired element
matrix_with_99 = np.full((3, 3), 99)
matrix_with_99

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [43]:
# we can use the shape of an existing array to fill the values
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
np.full(arr.shape, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [44]:
# we can also pass the array to be filled like it
# here arr is untouched. a new array filled with 99 is
# created and the new array has the same shape as arr
np.full_like(arr, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [45]:
# using np.arange to create array from range
# generate values between 0 and 10(exclusive) with a step of 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [46]:
# create samples between a start and stop
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [47]:
# fill an array with random numbers
# fills the array with float values between 0 and 1
np.random.rand(3, 3)

array([[0.22722826, 0.09724221, 0.2846299 ],
       [0.11654552, 0.95752413, 0.59219373],
       [0.64770832, 0.66667554, 0.30294569]])

In [48]:
# fill an array with integers within a range
np.random.randint(-10, 10, size=(4, 4), dtype="int16")

array([[  7,   5, -10,  -2],
       [  8,   6, -10,  -1],
       [-10,  -4,   4,   7],
       [ -4,  -2,   3,  -4]], dtype=int16)

In [49]:
# identity matrix of a particular size
# below generates a 4x4 identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
# repeat a particular number
print(np.repeat(5, 10))

arr = np.array([[10, 20], [30, 40]])

# every element in the array is repeated twice
# output array is flattened by default (i.e) when axis is None
print(np.repeat(arr, 2))

# repeats a row n times and then proceeds to repeat next row n times
# [[10, 20], [10, 20], [30, 40], [30, 40]]
print(np.repeat(arr, 2, axis=0))

# repeats a column element n times, then moves on to repeat the next element
# outputs [[10, 10, 20, 20], [30, 30, 40, 40]]
print(np.repeat(arr, 2, axis=1))

[5 5 5 5 5 5 5 5 5 5]
[10 10 20 20 30 30 40 40]
[[10 20]
 [10 20]
 [30 40]
 [30 40]]
[[10 10 20 20]
 [30 30 40 40]]


In [51]:
def my_function(z, y, x):
    # This function is called exactly one per entire array.
    # each of x, y and z is nd-array of shape (3,2,10)
    print("x", x)
    print("y", y)
    print("z", z)
    return x * y + z


np.fromfunction(my_function, (3, 2, 10));

x [[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]

 [[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]

 [[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]
y [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
z [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]]


## Basic Mathematics

In [52]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [53]:
a + 2

array([3, 4, 5, 6])

In [54]:
a - 2

array([-1,  0,  1,  2])

In [55]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
a += 2
a

array([3, 4, 5, 6])

In [58]:
a ** 2

array([ 9, 16, 25, 36])

In [59]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [60]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [61]:
np.tan(a)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619])

In [62]:
# e^x
np.exp(a)

array([ 20.08553692,  54.59815003, 148.4131591 , 403.42879349])

In [63]:
# natural log (i.e) log base e
print(np.log(a))

np.log10(a)

[1.09861229 1.38629436 1.60943791 1.79175947]


array([0.47712125, 0.60205999, 0.69897   , 0.77815125])

In [64]:
# adding two arrays
b = np.array([5, 6, 7, 8])
a + b

array([ 8, 10, 12, 14])

In [65]:
a - b

array([-2, -2, -2, -2])

## Linear algebra functions

In [66]:
a = np.ones((2, 3))
print(a)
b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [67]:
# `a * b` will raise error
print(np.matmul(a, b))

# This also performs matrix multiplication
print(a.dot(b))

[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


In [68]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [69]:
np.equal(a, np.matmul(a, c))

array([[ True,  True,  True],
       [ True,  True,  True]])

## Statistics

In [70]:
numbers = np.array([[9, 8, 0], [7, 2, 3], [4, 5, 1]])
numbers

array([[9, 8, 0],
       [7, 2, 3],
       [4, 5, 1]])

In [71]:
# min of all the elements in the matrix
# rows are axis =1 and columns are axis = 0
print(np.min(numbers))

# finds minimum element in each column
print(np.min(numbers, axis=0))

# finds min element from each row
print(np.min(numbers, axis=1))

0
[4 2 0]
[0 2 1]


In [72]:
print(np.max(numbers))

# finds maximum element in each column
print(np.max(numbers, axis=0))

# finds max element from each row
print(np.max(numbers, axis=1))

9
[9 8 3]
[9 7 5]


![numpy sum with axis0](numpy_sum_axis_0.png)
![numpy sum with axis1](numpy_sum_axis_1.png)

In [73]:
# sum of entire matrix
print(np.sum(numbers))

# column wise sum, because when axis = 0, we move vertically
# downwards, thereby aggregating all the rows to a single row
print(np.sum(numbers, axis=0))

# row wise sum,  because axis=1 folds/aggregate
# each column moving from left to right.
print(np.sum(numbers, axis=1))

39
[20 15  4]
[17 12 10]


In [74]:
# sqrt of each element in the array
np.sqrt(numbers)

array([[3.        , 2.82842712, 0.        ],
       [2.64575131, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 1.        ]])

In [75]:
# standard deviation
np.std(numbers)

# calculates variance
np.var(numbers)

np.mean(numbers)

np.median(numbers)

# Calculates 25th and 75the percentiles.
np.percentile(numbers, [25, 75])

array([2., 7.])

## Reorganizing arrays

In [76]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

# new dimension should cover all the elements from the original array
after = before.reshape((8, 1))
print(after)

# In reshape, exactly one dimension can be specified as -1
# numpy finds the length/size of the ndarray and substitutes it for -1
two_d_arr = np.array([[1, 2], [3, 4]])
# here -1 will be substituted with 4(two_d_arr.size) / 1
# so the resulting shape will be (4, 1)
# This trick is used to convert a 1d array to a column vector
print(two_d_arr.reshape((-1, 1)).shape)

# here -1 will be substituted with 4(two_d_arr.size)/ 1 (product of known dimensions)
# so the resulting shape will be (1, 4)
# This trick is often used to convert a training example/instance
# into a 2d array for prediction.
print(two_d_arr.reshape((1, -1)).shape)

arr = np.arange(24).reshape(2, 3, 4)
print(arr.shape)

# here -1 will be filled with 24 / (3 * 4) = 2
print(arr.reshape(3, 4, -1).shape)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(4, 1)
(1, 4)
(2, 3, 4)
(3, 4, 2)


In [77]:
# vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
# horizontally stack vectors
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
# You can split an array into several smaller arrays using hsplit.
arr = np.array(
    [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]
)

# splits the array into 3 equally shaped arrays
# Imagine breaking a horizontal line from left to right
# splits the array horizontally in to 3 parts
# Number of splits here should be a divisor of the number of columns
print(np.hsplit(arr, 3))

# splits the array vertically in to 2 parts
# imagine breaking a vertical bar from top to bottom
# here we have only two rows, so we can divide equally
# by 2 only. If we give any number more than the rows, we will get error
# Number of splits here should be a divisor of the number of rows
print(np.vsplit(arr, 2))

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]


In [80]:
# explore row_stack and column_stack
a = np.arange(1, 5)
b = np.arange(5, 9)
# row stack - Stack 1-D arrays as rows into a 2-D array.
print(np.row_stack([a, b]))

# column stack - Stack 1-D arrays as columns into a 2-D array.
print(np.column_stack([a, b]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [81]:
# concatenate multiple 1d array to 2d array using concatenate
a = np.arange(1, 11).reshape(2, 5)
b = np.arange(10, 14).reshape(2, 2)
c = np.arange(15, 20).reshape(1, 5)

print(a)
print(b)
print(c)

# In a nd-array, when concatenating along axis=0, all other n-1 axis values
# should match for all the arrays to be concatenated.
# In case of 2d arrays, if we are concatenating along axis=0, then
# all the 2d arrays should have same number of columns
# Here a and c can be concatenated along axis=0 but not a and b
print(np.concatenate((a, c), axis=0))

# a and b can be concatenated along axis=1 because both have same
# number of rows(i.e along axis=0)
print(np.concatenate((a, b), axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11]
 [12 13]]
[[15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [15 16 17 18 19]]
[[ 1  2  3  4  5 10 11]
 [ 6  7  8  9 10 12 13]]


In [82]:
arr = np.arange(1, 25).reshape(2, 12)

# view for shallow copying
shallow_copy_arr = arr.view()
shallow_copy_arr[0, 0] = 10
print(shallow_copy_arr)
print(arr)

# copy for deep copying
deep_copy_arr = arr.copy()
deep_copy_arr[0, 0] = 0
print(deep_copy_arr)
print(arr)

[[10  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[10  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 0  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[10  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


## Loading data from a file

For loading file, we generally use pandas library. But numpy also has the capability to read csv files.

In [83]:
# load data from a file
# default reads the numbers as floats
filedata = np.genfromtxt("data.txt", delimiter=",").astype("int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## Boolean masking and advanced indexing

In [84]:
# we can use relational operators
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [85]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [86]:
# columnwise value check
print(filedata.shape)

# operates vertically on all rows similar to `np.sum`
print(np.any(filedata > 50, axis=0))

# Operates on all columns of a row
print(np.any(filedata > 50, axis=1))

(3, 18)
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[ True  True  True]


In [87]:
# columnwise value check
print(filedata.shape)

# prints true for that column if all the values in that column
# satisfies the condition
print(np.all(filedata > 50, axis=0))

# rowwise condition check. We should get True/False for every row
print(np.all(filedata > 50, axis=1))

(3, 18)
[False False False False  True False False False False False False False
 False False False False False False]
[False False False]


In [88]:
# returns a array of same dimension and shape as filedata
# but every element in the array is a boolean element.
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [89]:
# & - AND
# | - OR
filedata[(filedata > 50) & (filedata < 100)]

array([75, 75, 55, 78, 76, 88], dtype=int32)

In [90]:
# np.where can be used to print indices of
# elements that satisfy the condition
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# returns a tuple of arrays. One array contains the index of each dimension
# here we have first array for row indices and second array for column
# indices
positions = np.where(a % 2)

for row, col in zip(positions[0], positions[1]):
    print(f"({row}, {col})")

# returns empty tuple when no elements satisfy the constraint
positions = np.where(a > 50)
positions

(0, 0)
(0, 2)
(1, 0)
(1, 2)
(2, 0)
(2, 2)


(array([], dtype=int64), array([], dtype=int64))

## Broadcasting

In [91]:
# NumPy understands that the scalar multiplication with a matrix should
# happen with each cell(matrix element). That concept is called broadcasting.
# Broadcasting is a mechanism that allows NumPy to perform operations
# on arrays of different shapes. The dimensions of your array
# must be compatible, for example, when the dimensions of both
# arrays are equal or when one of them is 1.

# Example Operations like scalar multiplication of a matrix or a vector
v = np.array([1, 2])
# all elements of the vector are multiplied by 3
v * 3

array([3, 6])

## Generating random numbers

In [92]:
rng = np.random.default_rng()
rng.integers(0, 20, (4, 5))

array([[13, 19, 19, 12,  6],
       [ 5,  9, 16,  3, 10],
       [ 3, 10, 12, 11, 18],
       [ 8,  5,  8,  3, 16]])

In [93]:
# generates values between 0 and 1
# uniform distribution
rng.random((3, 2))

array([[0.35502754, 0.76837308],
       [0.25305996, 0.30136896],
       [0.33732282, 0.4016389 ]])

In [94]:
# z-distribution or standard normal distribution
rng.standard_normal((3, 4))

array([[-0.38571866, -0.41364706,  0.18390162,  0.05851635],
       [ 1.53345603,  0.10216332,  0.08164773,  0.60717055],
       [ 0.23476429, -0.83556209, -0.54897218, -0.00580552]])

## Unique items and counts

In [95]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

# returns indices of unique values in the array along with the unique values
np.unique(a, return_index=True)

[11 12 13 14 15 16 17 18 19 20]


(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [96]:
unique_values, values_count = np.unique(a, return_counts=True)
print(unique_values, values_count)

[11 12 13 14 15 16 17 18 19 20] [3 2 2 2 1 1 1 1 1 1]


In [97]:
a2d = np.array([[1, 2, 3, 2], [5, 6, 7, 6], [9, 10, 11, 10], [1, 2, 3, 2]])

# returns only unique rows
np.unique(a2d, axis=0)

array([[ 1,  2,  3,  2],
       [ 5,  6,  7,  6],
       [ 9, 10, 11, 10]])

In [98]:
# returns only unique columns
np.unique(a2d, axis=1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 1,  2,  3]])

## Transpose and reshape

In [99]:
arr = np.arange(6).reshape((2, 3))

In [100]:
np.transpose(arr)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [101]:
np.reshape(arr, (3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [102]:
print(arr.transpose())

# This also does the transpose
arr.T

[[0 3]
 [1 4]
 [2 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

## Reversing array

In [103]:
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.flip(arr2D)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [104]:
# reverse row order
np.flip(arr2D, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [105]:
# reverse column order
np.flip(arr2D, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [106]:
# reverse a particular row
arr2D[1] = np.flip(arr2D[1])
arr2D

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [107]:
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# reverse a particular column
arr2D[:, 1] = np.flip(arr2D[:, 1])
arr2D

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  2, 11, 12]])

## Flattening multidimensional arrays

In [108]:
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# flatten creates a deep copy of the original array
arr2D.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
# ravel creates a shallow copy of the original array
# hence changes to the new array will be reflected in the source
# memory efficient due to its shallow copy. Use in read only cases
new_arr = arr2D.ravel()
new_arr[0] = 100
print(new_arr)
print(arr2D)

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## Save and load numpy objects

* `loadtxt` and `savetxt` handle normal text file formats(txt, csv etc).
* `load` and `save` functions handle binary files with .npy extension. `save` is used to store one nd-array
* `savez` handles numpy files with .npz extension. This method is used to store many nd-arrays.

```Python
# Numpy methods
np.save()
np.savez()
np.savez_compressed()
np.savetxt()
np.load()
np.loadtxt()
```